services:
        buildall:
                image: ubuntu:22.04
                container_name: mubuild
                volumes:
                        - ./:/root/
                restart: "no"
                command: bash scripts/docker_setup.sh && python3 build_uefi.py -s all
                environment:
                        TZ: Asia/Shanghai
                        DEBIAN_FRONTEND: noninteractive
